# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-16 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('victory_points', models.IntegerField()),
                ('brick', models.IntegerField()),
                ('wood', models.IntegerField()),
                ('wheat', models.IntegerField()),
                ('sheep', models.IntegerField()),
                ('stone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brick', models.IntegerField()),
                ('wood', models.IntegerField()),
                ('wheat', models.IntegerField()),
                ('sheep', models.IntegerField()),
                ('stone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('resource_type', models.CharField(max_length=8)),
                ('dice_value', models.IntegerField()),
                ('has_robber', models.BooleanField(default=False)),
                ('edge', models.ManyToManyField(to='catan.Edge')),
            ],
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('has_city', models.BooleanField()),
                ('settlement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catan.Player')),
            ],
        ),
        migrations.AddField(
            model_name='tile',
            name='vertex',
            field=models.ManyToManyField(to='catan.Vertex'),
        ),
        migrations.AddField(
            model_name='edge',
            name='road',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catan.Player'),
        ),
    ]
