# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-16 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='number',
        ),
    ]
