# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0002_remove_tile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
