# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-02 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0003_auto_20170714_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.AlterField(
            model_name='edge',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='has_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vertex',
            name='settlement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catan.Player'),
        ),
    ]
