# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-16 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=16)),
                ('lname', models.CharField(max_length=16)),
                ('email_address', models.EmailField(default=None, max_length=254)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
