# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-20 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_name', models.CharField(max_length=32)),
                ('post_dt', models.DateTimeField(auto_now_add=True)),
                ('post_content', models.CharField(max_length=512)),
            ],
        ),
    ]
